export interface CountryInfo {
  name: string;
  iso3: string;
  flag: string;
}

export const countryData: CountryInfo[] = [
  { name: 'Afghanistan', iso3: 'AFG', flag: '🇦🇫' },
  { name: 'Albania', iso3: 'ALB', flag: '🇦🇱' },
  { name: 'Algeria', iso3: 'DZA', flag: '🇩🇿' },
  { name: 'Andorra', iso3: 'AND', flag: '🇦🇩' },
  { name: 'Angola', iso3: 'AGO', flag: '🇦🇴' },
  { name: 'Antigua and Barbuda', iso3: 'ATG', flag: '🇦🇬' },
  { name: 'Argentina', iso3: 'ARG', flag: '🇦🇷' },
  { name: 'Armenia', iso3: 'ARM', flag: '🇦🇲' },
  { name: 'Australia', iso3: 'AUS', flag: '🇦🇺' },
  { name: 'Austria', iso3: 'AUT', flag: '🇦🇹' },
  { name: 'Azerbaijan', iso3: 'AZE', flag: '🇦🇿' },
  { name: 'Bahamas', iso3: 'BHS', flag: '🇧🇸' },
  { name: 'Bahrain', iso3: 'BHR', flag: '🇧🇭' },
  { name: 'Bangladesh', iso3: 'BGD', flag: '🇧🇩' },
  { name: 'Barbados', iso3: 'BRB', flag: '🇧🇧' },
  { name: 'Belarus', iso3: 'BLR', flag: '🇧🇾' },
  { name: 'Belgium', iso3: 'BEL', flag: '🇧🇪' },
  { name: 'Belize', iso3: 'BLZ', flag: '🇧🇿' },
  { name: 'Benin', iso3: 'BEN', flag: '🇧🇯' },
  { name: 'Bhutan', iso3: 'BTN', flag: '🇧🇹' },
  { name: 'Bolivia', iso3: 'BOL', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', iso3: 'BIH', flag: '🇧🇦' },
  { name: 'Botswana', iso3: 'BWA', flag: '🇧🇼' },
  { name: 'Brazil', iso3: 'BRA', flag: '🇧🇷' },
  { name: 'Brunei', iso3: 'BRN', flag: '🇧🇳' },
  { name: 'Bulgaria', iso3: 'BGR', flag: '🇧🇬' },
  { name: 'Burkina Faso', iso3: 'BFA', flag: '🇧🇫' },
  { name: 'Burundi', iso3: 'BDI', flag: '🇧🇮' },
  { name: 'Cabo Verde', iso3: 'CPV', flag: '🇨🇻' },
  { name: 'Cambodia', iso3: 'KHM', flag: '🇰🇭' },
  { name: 'Cameroon', iso3: 'CMR', flag: '🇨🇲' },
  { name: 'Canada', iso3: 'CAN', flag: '🇨🇦' },
  { name: 'Central African Republic', iso3: 'CAF', flag: '🇨🇫' },
  { name: 'Chad', iso3: 'TCD', flag: '🇹🇩' },
  { name: 'Chile', iso3: 'CHL', flag: '🇨🇱' },
  { name: 'China', iso3: 'CHN', flag: '🇨🇳' },
  { name: 'Colombia', iso3: 'COL', flag: '🇨🇴' },
  { name: 'Comoros', iso3: 'COM', flag: '🇰🇲' },
  { name: 'Congo', iso3: 'COG', flag: '🇨🇬' },
  { name: 'Costa Rica', iso3: 'CRI', flag: '🇨🇷' },
  { name: 'Croatia', iso3: 'HRV', flag: '🇭🇷' },
  { name: 'Cuba', iso3: 'CUB', flag: '🇨🇺' },
  { name: 'Cyprus', iso3: 'CYP', flag: '🇨🇾' },
  { name: 'Czech Republic', iso3: 'CZE', flag: '🇨🇿' },
  { name: 'Democratic Republic of the Congo', iso3: 'COD', flag: '🇨🇩' },
  { name: 'Denmark', iso3: 'DNK', flag: '🇩🇰' },
  { name: 'Djibouti', iso3: 'DJI', flag: '🇩🇯' },
  { name: 'Dominica', iso3: 'DMA', flag: '🇩🇲' },
  { name: 'Dominican Republic', iso3: 'DOM', flag: '🇩🇴' },
  { name: 'Ecuador', iso3: 'ECU', flag: '🇪🇨' },
  { name: 'Egypt', iso3: 'EGY', flag: '🇪🇬' },
  { name: 'El Salvador', iso3: 'SLV', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', iso3: 'GNQ', flag: '🇬🇶' },
  { name: 'Eritrea', iso3: 'ERI', flag: '🇪🇷' },
  { name: 'Estonia', iso3: 'EST', flag: '🇪🇪' },
  { name: 'Eswatini', iso3: 'SWZ', flag: '🇸🇿' },
  { name: 'Ethiopia', iso3: 'ETH', flag: '🇪🇹' },
  { name: 'Fiji', iso3: 'FJI', flag: '🇫🇯' },
  { name: 'Finland', iso3: 'FIN', flag: '🇫🇮' },
  { name: 'France', iso3: 'FRA', flag: '🇫🇷' },
  { name: 'Gabon', iso3: 'GAB', flag: '🇬🇦' },
  { name: 'Gambia', iso3: 'GMB', flag: '🇬🇲' },
  { name: 'Georgia', iso3: 'GEO', flag: '🇬🇪' },
  { name: 'Germany', iso3: 'DEU', flag: '🇩🇪' },
  { name: 'Ghana', iso3: 'GHA', flag: '🇬🇭' },
  { name: 'Greece', iso3: 'GRC', flag: '🇬🇷' },
  { name: 'Grenada', iso3: 'GRD', flag: '🇬🇩' },
  { name: 'Guatemala', iso3: 'GTM', flag: '🇬🇹' },
  { name: 'Guinea', iso3: 'GIN', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', iso3: 'GNB', flag: '🇬🇼' },
  { name: 'Guyana', iso3: 'GUY', flag: '🇬🇾' },
  { name: 'Haiti', iso3: 'HTI', flag: '🇭🇹' },
  { name: 'Honduras', iso3: 'HND', flag: '🇭🇳' },
  { name: 'Hungary', iso3: 'HUN', flag: '🇭🇺' },
  { name: 'Iceland', iso3: 'ISL', flag: '🇮🇸' },
  { name: 'India', iso3: 'IND', flag: '🇮🇳' },
  { name: 'Indonesia', iso3: 'IDN', flag: '🇮🇩' },
  { name: 'Iran', iso3: 'IRN', flag: '🇮🇷' },
  { name: 'Iraq', iso3: 'IRQ', flag: '🇮🇶' },
  { name: 'Ireland', iso3: 'IRL', flag: '🇮🇪' },
  { name: 'Israel', iso3: 'ISR', flag: '🇮🇱' },
  { name: 'Italy', iso3: 'ITA', flag: '🇮🇹' },
  { name: 'Jamaica', iso3: 'JAM', flag: '🇯🇲' },
  { name: 'Japan', iso3: 'JPN', flag: '🇯🇵' },
  { name: 'Jordan', iso3: 'JOR', flag: '🇯🇴' },
  { name: 'Kazakhstan', iso3: 'KAZ', flag: '🇰🇿' },
  { name: 'Kenya', iso3: 'KEN', flag: '🇰🇪' },
  { name: 'Kiribati', iso3: 'KIR', flag: '🇰🇮' },
  { name: 'Kuwait', iso3: 'KWT', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', iso3: 'KGZ', flag: '🇰🇬' },
  { name: 'Laos', iso3: 'LAO', flag: '🇱🇦' },
  { name: 'Latvia', iso3: 'LVA', flag: '🇱🇻' },
  { name: 'Lebanon', iso3: 'LBN', flag: '🇱🇧' },
  { name: 'Lesotho', iso3: 'LSO', flag: '🇱🇸' },
  { name: 'Liberia', iso3: 'LBR', flag: '🇱🇷' },
  { name: 'Libya', iso3: 'LBY', flag: '🇱🇾' },
  { name: 'Liechtenstein', iso3: 'LIE', flag: '🇱🇮' },
  { name: 'Lithuania', iso3: 'LTU', flag: '🇱🇹' },
  { name: 'Luxembourg', iso3: 'LUX', flag: '🇱🇺' },
  { name: 'Madagascar', iso3: 'MDG', flag: '🇲🇬' },
  { name: 'Malawi', iso3: 'MWI', flag: '🇲🇼' },
  { name: 'Malaysia', iso3: 'MYS', flag: '🇲🇾' },
  { name: 'Maldives', iso3: 'MDV', flag: '🇲🇻' },
  { name: 'Mali', iso3: 'MLI', flag: '🇲🇱' },
  { name: 'Malta', iso3: 'MLT', flag: '🇲🇹' },
  { name: 'Marshall Islands', iso3: 'MHL', flag: '🇲🇭' },
  { name: 'Mauritania', iso3: 'MRT', flag: '🇲🇷' },
  { name: 'Mauritius', iso3: 'MUS', flag: '🇲🇺' },
  { name: 'Mexico', iso3: 'MEX', flag: '🇲🇽' },
  { name: 'Micronesia', iso3: 'FSM', flag: '🇫🇲' },
  { name: 'Moldova', iso3: 'MDA', flag: '🇲🇩' },
  { name: 'Monaco', iso3: 'MCO', flag: '🇲🇨' },
  { name: 'Mongolia', iso3: 'MNG', flag: '🇲🇳' },
  { name: 'Montenegro', iso3: 'MNE', flag: '🇲🇪' },
  { name: 'Morocco', iso3: 'MAR', flag: '🇲🇦' },
  { name: 'Mozambique', iso3: 'MOZ', flag: '🇲🇿' },
  { name: 'Myanmar', iso3: 'MMR', flag: '🇲🇲' },
  { name: 'Namibia', iso3: 'NAM', flag: '🇳🇦' },
  { name: 'Nauru', iso3: 'NRU', flag: '🇳🇷' },
  { name: 'Nepal', iso3: 'NPL', flag: '🇳🇵' },
  { name: 'Netherlands', iso3: 'NLD', flag: '🇳🇱' },
  { name: 'New Zealand', iso3: 'NZL', flag: '🇳🇬' },
  { name: 'Nicaragua', iso3: 'NIC', flag: '🇳🇮' },
  { name: 'Niger', iso3: 'NER', flag: '🇳🇪' },
  { name: 'Nigeria', iso3: 'NGA', flag: '🇳🇬' },
  { name: 'North Korea', iso3: 'PRK', flag: '🇰🇵' },
  { name: 'North Macedonia', iso3: 'MKD', flag: '🇲🇰' },
  { name: 'Norway', iso3: 'NOR', flag: '🇳🇴' },
  { name: 'Oman', iso3: 'OMN', flag: '🇴🇲' },
  { name: 'Pakistan', iso3: 'PAK', flag: '🇵🇰' },
  { name: 'Palau', iso3: 'PLW', flag: '🇵🇼' },
  { name: 'Panama', iso3: 'PAN', flag: '🇵🇦' },
  { name: 'Papua New Guinea', iso3: 'PNG', flag: '🇵🇬' },
  { name: 'Paraguay', iso3: 'PRY', flag: '🇵🇾' },
  { name: 'Peru', iso3: 'PER', flag: '🇵🇪' },
  { name: 'Philippines', iso3: 'PHL', flag: '🇵🇭' },
  { name: 'Poland', iso3: 'POL', flag: '🇵🇱' },
  { name: 'Portugal', iso3: 'PRT', flag: '🇵🇹' },
  { name: 'Qatar', iso3: 'QAT', flag: '🇶🇦' },
  { name: 'Romania', iso3: 'ROU', flag: '🇷🇴' },
  { name: 'Russia', iso3: 'RUS', flag: '🇷🇺' },
  { name: 'Rwanda', iso3: 'RWA', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', iso3: 'KNA', flag: '🇰🇳' },
  { name: 'Saint Lucia', iso3: 'LCA', flag: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', iso3: 'VCT', flag: '🇻🇨' },
  { name: 'Samoa', iso3: 'WSM', flag: '🇼🇸' },
  { name: 'San Marino', iso3: 'SMR', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', iso3: 'STP', flag: '🇸🇹' },
  { name: 'Saudi Arabia', iso3: 'SAU', flag: '🇸🇦' },
  { name: 'Senegal', iso3: 'SEN', flag: '🇸🇳' },
  { name: 'Serbia', iso3: 'SRB', flag: '🇷🇸' },
  { name: 'Seychelles', iso3: 'SYC', flag: '🇸🇨' },
  { name: 'Sierra Leone', iso3: 'SLE', flag: '🇸🇱' },
  { name: 'Singapore', iso3: 'SGP', flag: '🇸🇬' },
  { name: 'Slovakia', iso3: 'SVK', flag: '🇸🇰' },
  { name: 'Slovenia', iso3: 'SVN', flag: '🇸🇮' },
  { name: 'Solomon Islands', iso3: 'SLB', flag: '🇸🇧' },
  { name: 'Somalia', iso3: 'SOM', flag: '🇸🇴' },
  { name: 'South Africa', iso3: 'ZAF', flag: '🇿🇦' },
  { name: 'South Korea', iso3: 'KOR', flag: '🇰🇷' },
  { name: 'South Sudan', iso3: 'SSD', flag: '🇸🇸' },
  { name: 'Spain', iso3: 'ESP', flag: '🇪🇸' },
  { name: 'Sri Lanka', iso3: 'LKA', flag: '🇱🇰' },
  { name: 'Sudan', iso3: 'SDN', flag: '🇸🇩' },
  { name: 'Suriname', iso3: 'SUR', flag: '🇸🇷' },
  { name: 'Sweden', iso3: 'SWE', flag: '🇸🇪' },
  { name: 'Switzerland', iso3: 'CHE', flag: '🇨🇭' },
  { name: 'Syria', iso3: 'SYR', flag: '🇸🇾' },
  { name: 'Taiwan', iso3: 'TWN', flag: '🇹🇼' },
  { name: 'Tajikistan', iso3: 'TJK', flag: '🇹🇯' },
  { name: 'Tanzania', iso3: 'TZA', flag: '🇹🇿' },
  { name: 'Thailand', iso3: 'THA', flag: '🇹🇭' },
  { name: 'Timor-Leste', iso3: 'TLS', flag: '🇹🇱' },
  { name: 'Togo', iso3: 'TGO', flag: '🇹🇬' },
  { name: 'Tonga', iso3: 'TON', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', iso3: 'TTO', flag: '🇹🇹' },
  { name: 'Tunisia', iso3: 'TUN', flag: '🇹🇳' },
  { name: 'Turkey', iso3: 'TUR', flag: '🇹🇷' },
  { name: 'Turkmenistan', iso3: 'TKM', flag: '🇹🇲' },
  { name: 'Tuvalu', iso3: 'TUV', flag: '🇹🇻' },
  { name: 'Uganda', iso3: 'UGA', flag: '🇺🇬' },
  { name: 'Ukraine', iso3: 'UKR', flag: '🇺🇦' },
  { name: 'United Arab Emirates', iso3: 'ARE', flag: '🇦🇪' },
  { name: 'United Kingdom', iso3: 'GBR', flag: '🇬🇧' },
  { name: 'United States', iso3: 'USA', flag: '🇺🇸' },
  { name: 'Uruguay', iso3: 'URY', flag: '🇺🇾' },
  { name: 'Uzbekistan', iso3: 'UZB', flag: '🇺🇿' },
  { name: 'Vanuatu', iso3: 'VUT', flag: '🇻🇺' },
  { name: 'Vatican City', iso3: 'VAT', flag: '🇻🇦' },
  { name: 'Venezuela', iso3: 'VEN', flag: '🇻🇪' },
  { name: 'Vietnam', iso3: 'VNM', flag: '🇻🇳' },
  { name: 'Yemen', iso3: 'YEM', flag: '🇾🇪' },
  { name: 'Zambia', iso3: 'ZMB', flag: '🇿🇲' },
  { name: 'Zimbabwe', iso3: 'ZWE', flag: '🇿🇼' }
];
